artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: 
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  command_api: mohamedhanyyy/chest-ctscan-images
  local_data_file_kaggle: artifacts/data_ingestion/


